#pragma once

#define LIMIT_AMOUNT_OF_LIGHTS 8
#define LIMIT_AMOUNT_OF_MATERIALS 8
#define LIMIT_AMOUNT_OF_TEXTURES 8
#define LIMIT_AMOUNT_OF_MESHES 8
#define LIMIT_AMOUNT_OF_STATIC_MESHES 8
#define LIMIT_AMOUNT_OF_SHADERS 8